package com.ogambientes.checklist.enums;

public enum TipoAmbiente {
    COZINHA,
    VARANDA,
    GOURMET,
    AREA_SERVICO,
    LAVANDERIA,
    SALA_ESTAR,
    HOME_THEATER,
    CINEMA,
    LIVING,
    HALL,
    ESCRITORIO,
    BRINQUEDOTECA,
    ROUPEIRO,
    CIRCULACAO,
    SUITE,
    SUITE_01,
    SUITE_02,
    SUITE_03,
    SUITE_04,
    CLOSET,
    CLOSET_01,
    CLOSET_02,
    CLOSET_03,
    CLOSET_04,
    BANHEIRO,
    BANHEIRO_O1,
    BANHEIRO_O2,
    BANHEIRO_O3,
    BANHEIRO_O4,
    BANHEIRO_O5,
    LAVABO,
    LAVABO_01,
    LAVABO_02,
    LAVABO_03
}
