package com.ogambientes.checklist.enums;

public enum TipoPainel {
    PAINEL_LISO,
    PAINEL_RIPADO,
    PAINEL_FRISO_10MM,
    PAINEL_RIPA_SOBREPOSTA,
    PAINEL_PROVENCAL,
    PAINEL_FRIZARE,
    PAINEL_TELINHA,
    PAINEL_MOLDURA_TELINHA,
    PAINEL_CURVO,
    PAINEL_MUXARABI,
    PAINEL_TRELICA,
    PAINEL_VIDRO,
    PAINEL_RAFINATTA,
    PAINEL_ELISSE,
    PAINEL_ELISSE_CURVE
}
