package com.ogambientes.checklist.enums;

public enum TipoAcessorio {
    PRATELEIRAS_VEGAS,
    PRATELEIRAS_CURVE,
    PRATELEIRAS_RAFINATTA,
    TAMPO_MAKEUP,
    SAPATEIRA_INCLINADA,
    SAPATEIRA_INCLINADA_RAFINATTA,
    TAMPO_RAFINATTA_TESTEIRA,
    PERFIL_CURVE,
    PERFIL_PAINEL,
    PROTETOR_STUCCO,
    DIVISOR_MDF,
    DIVISOR_ACRILICO,
    DIVISOR_TALHER_MDF,
    DIVISOR_TALHER_MADEIRA,
    DIVISOR_TALHER_ORGALINE,
    DIVISOR_TALHER_ABIALINE,
    ORGANIZADOR_PRATOS,
    PORTA_FACAS,
    CORTA_FOLHAS,
    PORTA_CONDIMENTOS,
    TAPETE_EMBORRACHADO,
    RODIZIO,
    SAPATA,
    TESTEIRA






}
