package com.ogambientes.checklist.enums;

public enum TipoCabideiro {
    CABIDEIRO_COMUM,
    CABIDEIRO_COMUM_PINTADO,
    CABIDEIRO_CLOSET_ABERTO_COMUM,
    CABIDEIRO_CLOSET_ABERTO_COMUM_PINTADO,
    CABIDEIRO_METAL_DESIGNE,
    CABIDEIRO_METAL_DESIGNE_LED,
    CABIDEIRO_ESPECIAL
}
